
# ============================================================
# SuperKart - Model Training and MLflow Tracking
# ============================================================

# ------------------------------------------------------------
# Standard library
# ------------------------------------------------------------
import os

# ------------------------------------------------------------
# Data manipulation
# ------------------------------------------------------------
import pandas as pd

# ------------------------------------------------------------
# Model preprocessing
# ------------------------------------------------------------
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

# ------------------------------------------------------------
# Model training and tuning
# ------------------------------------------------------------
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# ------------------------------------------------------------
# Regression evaluation metrics
# ------------------------------------------------------------
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ------------------------------------------------------------
# Model serialization and experiment tracking
# ------------------------------------------------------------
import joblib
import mlflow


# ============================================================
# 1. MLflow Configuration
# ============================================================

# IMPORTANT:
# Replace this URL with the CURRENT Ngrok URL generated
# when you start the MLflow server.
#
# Example:
# https://xxxx-xxxx.ngrok-free.app
#
# Do NOT use http://localhost:5000 if MLflow is exposed
# through Ngrok.

MLFLOW_TRACKING_URI = os.environ.get(
    "MLFLOW_TRACKING_URI",
    "YOUR_NGROK_URL"
)

if MLFLOW_TRACKING_URI == "YOUR_NGROK_URL":
    raise ValueError(
        "MLFLOW_TRACKING_URI is not configured. "
        "Set it to your current Ngrok MLflow URL."
    )

mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

mlflow.set_experiment(
    "superkart-sales-training-experiment"
)

print("\nMLflow Tracking URI:")
print(MLFLOW_TRACKING_URI)


# ============================================================
# 2. Load Train/Test Datasets
# ============================================================

# These files are generated by prep.py

Xtrain = pd.read_csv("Xtrain.csv")
Xtest = pd.read_csv("Xtest.csv")

ytrain = pd.read_csv(
    "ytrain.csv"
).squeeze("columns")

ytest = pd.read_csv(
    "ytest.csv"
).squeeze("columns")


# Ensure target values are numeric

ytrain = pd.to_numeric(
    ytrain,
    errors="raise"
)

ytest = pd.to_numeric(
    ytest,
    errors="raise"
)


print("\nDataset Information")
print("----------------------------")
print("Xtrain shape:", Xtrain.shape)
print("Xtest shape :", Xtest.shape)
print("ytrain shape:", ytrain.shape)
print("ytest shape :", ytest.shape)


# ============================================================
# 3. Define Feature Groups
# ============================================================

numeric_features = [
    "Product_Weight",
    "Product_Allocated_Area",
    "Product_MRP",
    "Store_Establishment_Year"
]

categorical_features = [
    "Product_Sugar_Content",
    "Product_Type",
    "Store_Size",
    "Store_Location_City_Type",
    "Store_Type"
]


# ============================================================
# 4. Validate Expected Features
# ============================================================

expected_features = (
    numeric_features +
    categorical_features
)

missing_train_features = [
    column
    for column in expected_features
    if column not in Xtrain.columns
]

missing_test_features = [
    column
    for column in expected_features
    if column not in Xtest.columns
]


if missing_train_features:
    raise ValueError(
        "Training dataset is missing columns: "
        f"{missing_train_features}"
    )


if missing_test_features:
    raise ValueError(
        "Testing dataset is missing columns: "
        f"{missing_test_features}"
    )


# ============================================================
# 5. Preprocessing Pipeline
# ============================================================

preprocessor = make_column_transformer(

    # Numerical features
    (
        StandardScaler(),
        numeric_features
    ),

    # Categorical features
    (
        OneHotEncoder(
            handle_unknown="ignore"
        ),
        categorical_features
    ),

    remainder="drop"
)


# ============================================================
# 6. XGBoost Regression Model
# ============================================================

xgb_model = xgb.XGBRegressor(

    # Regression objective
    objective="reg:squarederror",

    # Reproducibility
    random_state=42,

    # One level of parallelism is used here.
    # GridSearchCV will handle parallel processing.
    n_jobs=1
)


# ============================================================
# 7. Complete Model Pipeline
# ============================================================

model_pipeline = make_pipeline(
    preprocessor,
    xgb_model
)


# ============================================================
# 8. Hyperparameter Search Space
# ============================================================

# 2 x 2 x 2 = 8 combinations
#
# 5-fold CV:
#
# 8 combinations x 5 folds = 40 model fits
#
# This is significantly faster than a large grid.

param_grid = {

    "xgbregressor__n_estimators": [
        50,
        100
    ],

    "xgbregressor__max_depth": [
        3,
        5
    ],

    "xgbregressor__learning_rate": [
        0.05,
        0.1
    ]
}


# ============================================================
# 9. Start Main MLflow Run
# ============================================================

with mlflow.start_run(
    run_name="superkart-xgboost-regression"
):

    # --------------------------------------------------------
    # Log project information
    # --------------------------------------------------------

    mlflow.log_params({

        "dataset": "SuperKart",

        "target_variable":
            "Product_Store_Sales_Total",

        "model":
            "XGBoost Regressor",

        "cv_folds": 5,

        "scoring":
            "neg_root_mean_squared_error",

        "random_state": 42

    })


    # --------------------------------------------------------
    # Display GridSearch information
    # --------------------------------------------------------

    print("\n==========================================")
    print("Starting GridSearchCV")
    print("==========================================")

    print("Parameter combinations: 8")
    print("Cross-validation folds: 5")
    print("Total model fits: 40")
    print("Parallel jobs: -1")


    # --------------------------------------------------------
    # GridSearchCV
    # --------------------------------------------------------

    grid_search = GridSearchCV(

        estimator=model_pipeline,

        param_grid=param_grid,

        cv=5,

        scoring="neg_root_mean_squared_error",

        # Use available CPU cores for GridSearchCV
        n_jobs=-1,

        verbose=1,

        return_train_score=True
    )


    # --------------------------------------------------------
    # Train models
    # --------------------------------------------------------

    grid_search.fit(
        Xtrain,
        ytrain
    )


    print("\n==========================================")
    print("GridSearchCV Completed")
    print("==========================================")


    # ========================================================
    # 10. Best Parameters
    # ========================================================

    print("\nBest Parameters:")
    print("----------------------------")

    print(
        grid_search.best_params_
    )


    # ========================================================
    # 11. Best Cross-Validation RMSE
    # ========================================================

    best_cv_rmse = (
        -grid_search.best_score_
    )

    print("\nBest Cross-Validation RMSE:")
    print(best_cv_rmse)


    # Log best CV score

    mlflow.log_metric(
        "best_cv_rmse",
        float(best_cv_rmse)
    )


    # ========================================================
    # 12. Log All GridSearch Combinations
    #    as Nested MLflow Runs
    # ========================================================

    results = grid_search.cv_results_

    print("\nLogging GridSearch combinations to MLflow...")

    for index, parameter_set in enumerate(
        results["params"]
    ):

        mean_cv_rmse = (
            -results["mean_test_score"][index]
        )

        std_cv_rmse = (
            results["std_test_score"][index]
        )

        mean_train_rmse = (
            -results["mean_train_score"][index]
        )


        with mlflow.start_run(
            run_name=(
                f"parameter-combination-{index + 1}"
            ),
            nested=True
        ):

            # Log parameters
            mlflow.log_params(
                parameter_set
            )

            # Log metrics
            mlflow.log_metrics({

                "mean_cv_rmse":
                    float(mean_cv_rmse),

                "std_cv_rmse":
                    float(std_cv_rmse),

                "mean_train_rmse":
                    float(mean_train_rmse)

            })


    print(
        "All parameter combinations logged successfully."
    )


    # ========================================================
    # 13. Select Best Model
    # ========================================================

    best_model = (
        grid_search.best_estimator_
    )


    # ========================================================
    # 14. Generate Predictions
    # ========================================================

    train_predictions = (
        best_model.predict(Xtrain)
    )

    test_predictions = (
        best_model.predict(Xtest)
    )


    # ========================================================
    # 15. Training Metrics
    # ========================================================

    train_mae = mean_absolute_error(
        ytrain,
        train_predictions
    )

    train_mse = mean_squared_error(
        ytrain,
        train_predictions
    )

    # No NumPy dependency required
    train_rmse = train_mse ** 0.5

    train_r2 = r2_score(
        ytrain,
        train_predictions
    )


    # ========================================================
    # 16. Testing Metrics
    # ========================================================

    test_mae = mean_absolute_error(
        ytest,
        test_predictions
    )

    test_mse = mean_squared_error(
        ytest,
        test_predictions
    )

    # No NumPy dependency required
    test_rmse = test_mse ** 0.5

    test_r2 = r2_score(
        ytest,
        test_predictions
    )


    # ========================================================
    # 17. Display Model Performance
    # ========================================================

    print("\n==========================================")
    print("       SUPERKART MODEL PERFORMANCE")
    print("==========================================")


    print("\nTraining Performance:")
    print("----------------------------")

    print(
        f"MAE  : {train_mae:.4f}"
    )

    print(
        f"RMSE : {train_rmse:.4f}"
    )

    print(
        f"R2   : {train_r2:.4f}"
    )


    print("\nTesting Performance:")
    print("----------------------------")

    print(
        f"MAE  : {test_mae:.4f}"
    )

    print(
        f"RMSE : {test_rmse:.4f}"
    )

    print(
        f"R2   : {test_r2:.4f}"
    )


    # ========================================================
    # 18. Log Best Model Parameters
    # ========================================================

    mlflow.log_params(
        grid_search.best_params_
    )


    # ========================================================
    # 19. Log Final Metrics
    # ========================================================

    mlflow.log_metrics({

        # Training metrics
        "train_mae":
            float(train_mae),

        "train_mse":
            float(train_mse),

        "train_rmse":
            float(train_rmse),

        "train_r2":
            float(train_r2),

        # Testing metrics
        "test_mae":
            float(test_mae),

        "test_mse":
            float(test_mse),

        "test_rmse":
            float(test_rmse),

        "test_r2":
            float(test_r2)

    })


    # ========================================================
    # 20. Save Test Predictions
    # ========================================================

    predictions = pd.DataFrame({

        "Actual_Sales":
            ytest.reset_index(drop=True),

        "Predicted_Sales":
            test_predictions

    })


    predictions["Prediction_Error"] = (
        predictions["Actual_Sales"]
        -
        predictions["Predicted_Sales"]
    )


    predictions_path = (
        "SuperKart/model_building/"
        "test_predictions.csv"
    )


    predictions.to_csv(
        predictions_path,
        index=False
    )


    # Log predictions to MLflow

    mlflow.log_artifact(
        predictions_path,
        artifact_path="predictions"
    )


    # ========================================================
    # 21. Save Best Model
    # ========================================================

    deployment_directory = (
        "SuperKart/deployment"
    )


    os.makedirs(
        deployment_directory,
        exist_ok=True
    )


    model_path = os.path.join(
        deployment_directory,
        "best_superkart_sales_model_v1.joblib"
    )


    joblib.dump(
        best_model,
        model_path
    )


    # Log model artifact

    mlflow.log_artifact(
        model_path,
        artifact_path="model"
    )


    # ========================================================
    # 22. Final Output
    # ========================================================

    print("\n==========================================")
    print("        TRAINING COMPLETED")
    print("==========================================")

    print(
        f"\nModel saved successfully to:"
        f"\n{model_path}"
    )

    print(
        f"\nPredictions saved to:"
        f"\n{predictions_path}"
    )

    print(
        "\nMLflow experiment:"
        "\nsuperkart-sales-training-experiment"
    )

    print(
        "\nMLflow tracking URI:"
        f"\n{MLFLOW_TRACKING_URI}"
    )

    print("\n==========================================")
